/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SelfregRouteImport } from './routes/selfreg'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JwtDebugRouteImport } from './routes/jwt-debug'
import { Route as BecomeRouteImport } from './routes/become'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfregRoute = SelfregRouteImport.update({
  id: '/selfreg',
  path: '/selfreg',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDebugRoute = JwtDebugRouteImport.update({
  id: '/jwt-debug',
  path: '/jwt-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRoute = BecomeRouteImport.update({
  id: '/become',
  path: '/become',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/login': typeof LoginRoute
  '/selfreg': typeof SelfregRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/login': typeof LoginRoute
  '/selfreg': typeof SelfregRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become': typeof BecomeRoute
  '/jwt-debug': typeof JwtDebugRoute
  '/login': typeof LoginRoute
  '/selfreg': typeof SelfregRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/become' | '/jwt-debug' | '/login' | '/selfreg' | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/become' | '/jwt-debug' | '/login' | '/selfreg' | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/become'
    | '/jwt-debug'
    | '/login'
    | '/selfreg'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeRoute: typeof BecomeRoute
  JwtDebugRoute: typeof JwtDebugRoute
  LoginRoute: typeof LoginRoute
  SelfregRoute: typeof SelfregRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selfreg': {
      id: '/selfreg'
      path: '/selfreg'
      fullPath: '/selfreg'
      preLoaderRoute: typeof SelfregRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwt-debug': {
      id: '/jwt-debug'
      path: '/jwt-debug'
      fullPath: '/jwt-debug'
      preLoaderRoute: typeof JwtDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become': {
      id: '/become'
      path: '/become'
      fullPath: '/become'
      preLoaderRoute: typeof BecomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeRoute: BecomeRoute,
  JwtDebugRoute: JwtDebugRoute,
  LoginRoute: LoginRoute,
  SelfregRoute: SelfregRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
